
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef void GLvoid;
typedef signed char GLbyte;
typedef short GLshort;
typedef int GLint;
typedef unsigned char GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef int GLsizei;
typedef float GLfloat;
typedef float GLclampf;
typedef double GLdouble;
typedef double GLclampd;

extern void __attribute__((__stdcall__)) glClearIndex( GLfloat c );
extern void __attribute__((__stdcall__)) glClearColor( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha );
extern void __attribute__((__stdcall__)) glClear( GLbitfield mask );
extern void __attribute__((__stdcall__)) glIndexMask( GLuint mask );
extern void __attribute__((__stdcall__)) glColorMask( GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha );
extern void __attribute__((__stdcall__)) glAlphaFunc( GLenum func, GLclampf ref );
extern void __attribute__((__stdcall__)) glBlendFunc( GLenum sfactor, GLenum dfactor );
extern void __attribute__((__stdcall__)) glLogicOp( GLenum opcode );
extern void __attribute__((__stdcall__)) glCullFace( GLenum mode );
extern void __attribute__((__stdcall__)) glFrontFace( GLenum mode );
extern void __attribute__((__stdcall__)) glPointSize( GLfloat size );
extern void __attribute__((__stdcall__)) glLineWidth( GLfloat width );
extern void __attribute__((__stdcall__)) glLineStipple( GLint factor, GLushort pattern );
extern void __attribute__((__stdcall__)) glPolygonMode( GLenum face, GLenum mode );
extern void __attribute__((__stdcall__)) glPolygonOffset( GLfloat factor, GLfloat units );
extern void __attribute__((__stdcall__)) glPolygonStipple( const GLubyte *mask );
extern void __attribute__((__stdcall__)) glGetPolygonStipple( GLubyte *mask );
extern void __attribute__((__stdcall__)) glEdgeFlag( GLboolean flag );
extern void __attribute__((__stdcall__)) glEdgeFlagv( const GLboolean *flag );
extern void __attribute__((__stdcall__)) glScissor( GLint x, GLint y, GLsizei width, GLsizei height);
extern void __attribute__((__stdcall__)) glClipPlane( GLenum plane, const GLdouble *equation );
extern void __attribute__((__stdcall__)) glGetClipPlane( GLenum plane, GLdouble *equation );
extern void __attribute__((__stdcall__)) glDrawBuffer( GLenum mode );
extern void __attribute__((__stdcall__)) glReadBuffer( GLenum mode );
extern void __attribute__((__stdcall__)) glEnable( GLenum cap );
extern void __attribute__((__stdcall__)) glDisable( GLenum cap );
extern GLboolean __attribute__((__stdcall__)) glIsEnabled( GLenum cap );
extern void __attribute__((__stdcall__)) glEnableClientState( GLenum cap );
extern void __attribute__((__stdcall__)) glDisableClientState( GLenum cap );
extern void __attribute__((__stdcall__)) glGetBooleanv( GLenum pname, GLboolean *params );
extern void __attribute__((__stdcall__)) glGetDoublev( GLenum pname, GLdouble *params );
extern void __attribute__((__stdcall__)) glGetFloatv( GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetIntegerv( GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glPushAttrib( GLbitfield mask );
extern void __attribute__((__stdcall__)) glPopAttrib( void );
extern void __attribute__((__stdcall__)) glPushClientAttrib( GLbitfield mask );
extern void __attribute__((__stdcall__)) glPopClientAttrib( void );
extern GLint __attribute__((__stdcall__)) glRenderMode( GLenum mode );
extern GLenum __attribute__((__stdcall__)) glGetError( void );
extern const GLubyte* __attribute__((__stdcall__)) glGetString( GLenum name );
extern void __attribute__((__stdcall__)) glFinish( void );
extern void __attribute__((__stdcall__)) glFlush( void );
extern void __attribute__((__stdcall__)) glHint( GLenum target, GLenum mode );


extern void __attribute__((__stdcall__)) glClearDepth( GLclampd depth );
extern void __attribute__((__stdcall__)) glDepthFunc( GLenum func );
extern void __attribute__((__stdcall__)) glDepthMask( GLboolean flag );
extern void __attribute__((__stdcall__)) glDepthRange( GLclampd near_val, GLclampd far_val );


extern void __attribute__((__stdcall__)) glClearAccum( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
extern void __attribute__((__stdcall__)) glAccum( GLenum op, GLfloat value );


extern void __attribute__((__stdcall__)) glMatrixMode( GLenum mode );
extern void __attribute__((__stdcall__)) glOrtho( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val );
extern void __attribute__((__stdcall__)) glFrustum( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val );
extern void __attribute__((__stdcall__)) glViewport( GLint x, GLint y, GLsizei width, GLsizei height );
extern void __attribute__((__stdcall__)) glPushMatrix( void );
extern void __attribute__((__stdcall__)) glPopMatrix( void );
extern void __attribute__((__stdcall__)) glLoadIdentity( void );
extern void __attribute__((__stdcall__)) glLoadMatrixd( const GLdouble *m );
extern void __attribute__((__stdcall__)) glLoadMatrixf( const GLfloat *m );
extern void __attribute__((__stdcall__)) glMultMatrixd( const GLdouble *m );
extern void __attribute__((__stdcall__)) glMultMatrixf( const GLfloat *m );
extern void __attribute__((__stdcall__)) glRotated( GLdouble angle, GLdouble x, GLdouble y, GLdouble z );
extern void __attribute__((__stdcall__)) glRotatef( GLfloat angle, GLfloat x, GLfloat y, GLfloat z );
extern void __attribute__((__stdcall__)) glScaled( GLdouble x, GLdouble y, GLdouble z );
extern void __attribute__((__stdcall__)) glScalef( GLfloat x, GLfloat y, GLfloat z );
extern void __attribute__((__stdcall__)) glTranslated( GLdouble x, GLdouble y, GLdouble z );
extern void __attribute__((__stdcall__)) glTranslatef( GLfloat x, GLfloat y, GLfloat z );


extern GLboolean __attribute__((__stdcall__)) glIsList( GLuint list );
extern void __attribute__((__stdcall__)) glDeleteLists( GLuint list, GLsizei range );
extern GLuint __attribute__((__stdcall__)) glGenLists( GLsizei range );
extern void __attribute__((__stdcall__)) glNewList( GLuint list, GLenum mode );
extern void __attribute__((__stdcall__)) glEndList( void );
extern void __attribute__((__stdcall__)) glCallList( GLuint list );
extern void __attribute__((__stdcall__)) glCallLists( GLsizei n, GLenum type, const GLvoid *lists );
extern void __attribute__((__stdcall__)) glListBase( GLuint base );


extern void __attribute__((__stdcall__)) glBegin( GLenum mode );
extern void __attribute__((__stdcall__)) glEnd( void );
extern void __attribute__((__stdcall__)) glVertex2d( GLdouble x, GLdouble y );
extern void __attribute__((__stdcall__)) glVertex2f( GLfloat x, GLfloat y );
extern void __attribute__((__stdcall__)) glVertex2i( GLint x, GLint y );
extern void __attribute__((__stdcall__)) glVertex2s( GLshort x, GLshort y );
extern void __attribute__((__stdcall__)) glVertex3d( GLdouble x, GLdouble y, GLdouble z );
extern void __attribute__((__stdcall__)) glVertex3f( GLfloat x, GLfloat y, GLfloat z );
extern void __attribute__((__stdcall__)) glVertex3i( GLint x, GLint y, GLint z );
extern void __attribute__((__stdcall__)) glVertex3s( GLshort x, GLshort y, GLshort z );
extern void __attribute__((__stdcall__)) glVertex4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w );
extern void __attribute__((__stdcall__)) glVertex4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
extern void __attribute__((__stdcall__)) glVertex4i( GLint x, GLint y, GLint z, GLint w );
extern void __attribute__((__stdcall__)) glVertex4s( GLshort x, GLshort y, GLshort z, GLshort w );
extern void __attribute__((__stdcall__)) glVertex2dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glVertex2fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glVertex2iv( const GLint *v );
extern void __attribute__((__stdcall__)) glVertex2sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glVertex3dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glVertex3fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glVertex3iv( const GLint *v );
extern void __attribute__((__stdcall__)) glVertex3sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glVertex4dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glVertex4fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glVertex4iv( const GLint *v );
extern void __attribute__((__stdcall__)) glVertex4sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glNormal3b( GLbyte nx, GLbyte ny, GLbyte nz );
extern void __attribute__((__stdcall__)) glNormal3d( GLdouble nx, GLdouble ny, GLdouble nz );
extern void __attribute__((__stdcall__)) glNormal3f( GLfloat nx, GLfloat ny, GLfloat nz );
extern void __attribute__((__stdcall__)) glNormal3i( GLint nx, GLint ny, GLint nz );
extern void __attribute__((__stdcall__)) glNormal3s( GLshort nx, GLshort ny, GLshort nz );
extern void __attribute__((__stdcall__)) glNormal3bv( const GLbyte *v );
extern void __attribute__((__stdcall__)) glNormal3dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glNormal3fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glNormal3iv( const GLint *v );
extern void __attribute__((__stdcall__)) glNormal3sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glIndexd( GLdouble c );
extern void __attribute__((__stdcall__)) glIndexf( GLfloat c );
extern void __attribute__((__stdcall__)) glIndexi( GLint c );
extern void __attribute__((__stdcall__)) glIndexs( GLshort c );
extern void __attribute__((__stdcall__)) glIndexub( GLubyte c );
extern void __attribute__((__stdcall__)) glIndexdv( const GLdouble *c );
extern void __attribute__((__stdcall__)) glIndexfv( const GLfloat *c );
extern void __attribute__((__stdcall__)) glIndexiv( const GLint *c );
extern void __attribute__((__stdcall__)) glIndexsv( const GLshort *c );
extern void __attribute__((__stdcall__)) glIndexubv( const GLubyte *c );
extern void __attribute__((__stdcall__)) glColor3b( GLbyte red, GLbyte green, GLbyte blue );
extern void __attribute__((__stdcall__)) glColor3d( GLdouble red, GLdouble green, GLdouble blue );
extern void __attribute__((__stdcall__)) glColor3f( GLfloat red, GLfloat green, GLfloat blue );
extern void __attribute__((__stdcall__)) glColor3i( GLint red, GLint green, GLint blue );
extern void __attribute__((__stdcall__)) glColor3s( GLshort red, GLshort green, GLshort blue );
extern void __attribute__((__stdcall__)) glColor3ub( GLubyte red, GLubyte green, GLubyte blue );
extern void __attribute__((__stdcall__)) glColor3ui( GLuint red, GLuint green, GLuint blue );
extern void __attribute__((__stdcall__)) glColor3us( GLushort red, GLushort green, GLushort blue );
extern void __attribute__((__stdcall__)) glColor4b( GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha );
extern void __attribute__((__stdcall__)) glColor4d( GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha );
extern void __attribute__((__stdcall__)) glColor4f( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
extern void __attribute__((__stdcall__)) glColor4i( GLint red, GLint green, GLint blue, GLint alpha );
extern void __attribute__((__stdcall__)) glColor4s( GLshort red, GLshort green, GLshort blue, GLshort alpha );
extern void __attribute__((__stdcall__)) glColor4ub( GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha );
extern void __attribute__((__stdcall__)) glColor4ui( GLuint red, GLuint green, GLuint blue, GLuint alpha );
extern void __attribute__((__stdcall__)) glColor4us( GLushort red, GLushort green, GLushort blue, GLushort alpha );
extern void __attribute__((__stdcall__)) glColor3bv( const GLbyte *v );
extern void __attribute__((__stdcall__)) glColor3dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glColor3fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glColor3iv( const GLint *v );
extern void __attribute__((__stdcall__)) glColor3sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glColor3ubv( const GLubyte *v );
extern void __attribute__((__stdcall__)) glColor3uiv( const GLuint *v );
extern void __attribute__((__stdcall__)) glColor3usv( const GLushort *v );
extern void __attribute__((__stdcall__)) glColor4bv( const GLbyte *v );
extern void __attribute__((__stdcall__)) glColor4dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glColor4fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glColor4iv( const GLint *v );
extern void __attribute__((__stdcall__)) glColor4sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glColor4ubv( const GLubyte *v );
extern void __attribute__((__stdcall__)) glColor4uiv( const GLuint *v );
extern void __attribute__((__stdcall__)) glColor4usv( const GLushort *v );
extern void __attribute__((__stdcall__)) glTexCoord1d( GLdouble s );
extern void __attribute__((__stdcall__)) glTexCoord1f( GLfloat s );
extern void __attribute__((__stdcall__)) glTexCoord1i( GLint s );
extern void __attribute__((__stdcall__)) glTexCoord1s( GLshort s );
extern void __attribute__((__stdcall__)) glTexCoord2d( GLdouble s, GLdouble t );
extern void __attribute__((__stdcall__)) glTexCoord2f( GLfloat s, GLfloat t );
extern void __attribute__((__stdcall__)) glTexCoord2i( GLint s, GLint t );
extern void __attribute__((__stdcall__)) glTexCoord2s( GLshort s, GLshort t );
extern void __attribute__((__stdcall__)) glTexCoord3d( GLdouble s, GLdouble t, GLdouble r );
extern void __attribute__((__stdcall__)) glTexCoord3f( GLfloat s, GLfloat t, GLfloat r );
extern void __attribute__((__stdcall__)) glTexCoord3i( GLint s, GLint t, GLint r );
extern void __attribute__((__stdcall__)) glTexCoord3s( GLshort s, GLshort t, GLshort r );
extern void __attribute__((__stdcall__)) glTexCoord4d( GLdouble s, GLdouble t, GLdouble r, GLdouble q );
extern void __attribute__((__stdcall__)) glTexCoord4f( GLfloat s, GLfloat t, GLfloat r, GLfloat q );
extern void __attribute__((__stdcall__)) glTexCoord4i( GLint s, GLint t, GLint r, GLint q );
extern void __attribute__((__stdcall__)) glTexCoord4s( GLshort s, GLshort t, GLshort r, GLshort q );
extern void __attribute__((__stdcall__)) glTexCoord1dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glTexCoord1fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glTexCoord1iv( const GLint *v );
extern void __attribute__((__stdcall__)) glTexCoord1sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glTexCoord2dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glTexCoord2fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glTexCoord2iv( const GLint *v );
extern void __attribute__((__stdcall__)) glTexCoord2sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glTexCoord3dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glTexCoord3fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glTexCoord3iv( const GLint *v );
extern void __attribute__((__stdcall__)) glTexCoord3sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glTexCoord4dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glTexCoord4fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glTexCoord4iv( const GLint *v );
extern void __attribute__((__stdcall__)) glTexCoord4sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glRasterPos2d( GLdouble x, GLdouble y );
extern void __attribute__((__stdcall__)) glRasterPos2f( GLfloat x, GLfloat y );
extern void __attribute__((__stdcall__)) glRasterPos2i( GLint x, GLint y );
extern void __attribute__((__stdcall__)) glRasterPos2s( GLshort x, GLshort y );
extern void __attribute__((__stdcall__)) glRasterPos3d( GLdouble x, GLdouble y, GLdouble z );
extern void __attribute__((__stdcall__)) glRasterPos3f( GLfloat x, GLfloat y, GLfloat z );
extern void __attribute__((__stdcall__)) glRasterPos3i( GLint x, GLint y, GLint z );
extern void __attribute__((__stdcall__)) glRasterPos3s( GLshort x, GLshort y, GLshort z );
extern void __attribute__((__stdcall__)) glRasterPos4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w );
extern void __attribute__((__stdcall__)) glRasterPos4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
extern void __attribute__((__stdcall__)) glRasterPos4i( GLint x, GLint y, GLint z, GLint w );
extern void __attribute__((__stdcall__)) glRasterPos4s( GLshort x, GLshort y, GLshort z, GLshort w );
extern void __attribute__((__stdcall__)) glRasterPos2dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glRasterPos2fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glRasterPos2iv( const GLint *v );
extern void __attribute__((__stdcall__)) glRasterPos2sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glRasterPos3dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glRasterPos3fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glRasterPos3iv( const GLint *v );
extern void __attribute__((__stdcall__)) glRasterPos3sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glRasterPos4dv( const GLdouble *v );
extern void __attribute__((__stdcall__)) glRasterPos4fv( const GLfloat *v );
extern void __attribute__((__stdcall__)) glRasterPos4iv( const GLint *v );
extern void __attribute__((__stdcall__)) glRasterPos4sv( const GLshort *v );
extern void __attribute__((__stdcall__)) glRectd( GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2 );
extern void __attribute__((__stdcall__)) glRectf( GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2 );
extern void __attribute__((__stdcall__)) glRecti( GLint x1, GLint y1, GLint x2, GLint y2 );
extern void __attribute__((__stdcall__)) glRects( GLshort x1, GLshort y1, GLshort x2, GLshort y2 );
extern void __attribute__((__stdcall__)) glRectdv( const GLdouble *v1, const GLdouble *v2 );
extern void __attribute__((__stdcall__)) glRectfv( const GLfloat *v1, const GLfloat *v2 );
extern void __attribute__((__stdcall__)) glRectiv( const GLint *v1, const GLint *v2 );
extern void __attribute__((__stdcall__)) glRectsv( const GLshort *v1, const GLshort *v2 );


extern void __attribute__((__stdcall__)) glShadeModel( GLenum mode );
extern void __attribute__((__stdcall__)) glLightf( GLenum light, GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glLighti( GLenum light, GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glLightfv( GLenum light, GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glLightiv( GLenum light, GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glGetLightfv( GLenum light, GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetLightiv( GLenum light, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glLightModelf( GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glLightModeli( GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glLightModelfv( GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glLightModeliv( GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glMaterialf( GLenum face, GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glMateriali( GLenum face, GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glMaterialfv( GLenum face, GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glMaterialiv( GLenum face, GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glGetMaterialfv( GLenum face, GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetMaterialiv( GLenum face, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glColorMaterial( GLenum face, GLenum mode );


extern void __attribute__((__stdcall__)) glPixelZoom( GLfloat xfactor, GLfloat yfactor );
extern void __attribute__((__stdcall__)) glPixelStoref( GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glPixelStorei( GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glPixelTransferf( GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glPixelTransferi( GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glPixelMapfv( GLenum map, GLint mapsize, const GLfloat *values );
extern void __attribute__((__stdcall__)) glPixelMapuiv( GLenum map, GLint mapsize, const GLuint *values );
extern void __attribute__((__stdcall__)) glPixelMapusv( GLenum map, GLint mapsize, const GLushort *values );
extern void __attribute__((__stdcall__)) glGetPixelMapfv( GLenum map, GLfloat *values );
extern void __attribute__((__stdcall__)) glGetPixelMapuiv( GLenum map, GLuint *values );
extern void __attribute__((__stdcall__)) glGetPixelMapusv( GLenum map, GLushort *values );
extern void __attribute__((__stdcall__)) glBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap );
extern void __attribute__((__stdcall__)) glReadPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels );
extern void __attribute__((__stdcall__)) glDrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels );
extern void __attribute__((__stdcall__)) glCopyPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum type );


extern void __attribute__((__stdcall__)) glStencilFunc( GLenum func, GLint ref, GLuint mask );
extern void __attribute__((__stdcall__)) glStencilMask( GLuint mask );
extern void __attribute__((__stdcall__)) glStencilOp( GLenum fail, GLenum zfail, GLenum zpass );
extern void __attribute__((__stdcall__)) glClearStencil( GLint s );


extern void __attribute__((__stdcall__)) glTexGend( GLenum coord, GLenum pname, GLdouble param );
extern void __attribute__((__stdcall__)) glTexGenf( GLenum coord, GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glTexGeni( GLenum coord, GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glTexGendv( GLenum coord, GLenum pname, const GLdouble *params );
extern void __attribute__((__stdcall__)) glTexGenfv( GLenum coord, GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glTexGeniv( GLenum coord, GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glGetTexGendv( GLenum coord, GLenum pname, GLdouble *params );
extern void __attribute__((__stdcall__)) glGetTexGenfv( GLenum coord, GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetTexGeniv( GLenum coord, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glTexEnvf( GLenum target, GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glTexEnvi( GLenum target, GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glTexEnvfv( GLenum target, GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glTexEnviv( GLenum target, GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glGetTexEnvfv( GLenum target, GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetTexEnviv( GLenum target, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glTexParameterf( GLenum target, GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glTexParameteri( GLenum target, GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glTexParameterfv( GLenum target, GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glTexParameteriv( GLenum target, GLenum pname, const GLint *params );
extern void __attribute__((__stdcall__)) glGetTexParameterfv( GLenum target, GLenum pname, GLfloat *params);
extern void __attribute__((__stdcall__)) glGetTexParameteriv( GLenum target, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glGetTexLevelParameterfv( GLenum target, GLint level, GLenum pname, GLfloat *params );
extern void __attribute__((__stdcall__)) glGetTexLevelParameteriv( GLenum target, GLint level, GLenum pname, GLint *params );
extern void __attribute__((__stdcall__)) glTexImage1D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels );
extern void __attribute__((__stdcall__)) glTexImage2D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels );
extern void __attribute__((__stdcall__)) glGetTexImage( GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels );


extern void __attribute__((__stdcall__)) glMap1d( GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points );
extern void __attribute__((__stdcall__)) glMap1f( GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points );
extern void __attribute__((__stdcall__)) glMap2d( GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points );
extern void __attribute__((__stdcall__)) glMap2f( GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points );
extern void __attribute__((__stdcall__)) glGetMapdv( GLenum target, GLenum query, GLdouble *v );
extern void __attribute__((__stdcall__)) glGetMapfv( GLenum target, GLenum query, GLfloat *v );
extern void __attribute__((__stdcall__)) glGetMapiv( GLenum target, GLenum query, GLint *v );
extern void __attribute__((__stdcall__)) glEvalCoord1d( GLdouble u );
extern void __attribute__((__stdcall__)) glEvalCoord1f( GLfloat u );
extern void __attribute__((__stdcall__)) glEvalCoord1dv( const GLdouble *u );
extern void __attribute__((__stdcall__)) glEvalCoord1fv( const GLfloat *u );
extern void __attribute__((__stdcall__)) glEvalCoord2d( GLdouble u, GLdouble v );
extern void __attribute__((__stdcall__)) glEvalCoord2f( GLfloat u, GLfloat v );
extern void __attribute__((__stdcall__)) glEvalCoord2dv( const GLdouble *u );
extern void __attribute__((__stdcall__)) glEvalCoord2fv( const GLfloat *u );
extern void __attribute__((__stdcall__)) glMapGrid1d( GLint un, GLdouble u1, GLdouble u2 );
extern void __attribute__((__stdcall__)) glMapGrid1f( GLint un, GLfloat u1, GLfloat u2 );
extern void __attribute__((__stdcall__)) glMapGrid2d( GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2 );
extern void __attribute__((__stdcall__)) glMapGrid2f( GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2 );
extern void __attribute__((__stdcall__)) glEvalPoint1( GLint i );
extern void __attribute__((__stdcall__)) glEvalPoint2( GLint i, GLint j );
extern void __attribute__((__stdcall__)) glEvalMesh1( GLenum mode, GLint i1, GLint i2 );
extern void __attribute__((__stdcall__)) glEvalMesh2( GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2 );


extern void __attribute__((__stdcall__)) glFogf( GLenum pname, GLfloat param );
extern void __attribute__((__stdcall__)) glFogi( GLenum pname, GLint param );
extern void __attribute__((__stdcall__)) glFogfv( GLenum pname, const GLfloat *params );
extern void __attribute__((__stdcall__)) glFogiv( GLenum pname, const GLint *params );


extern void __attribute__((__stdcall__)) glFeedbackBuffer( GLsizei size, GLenum type, GLfloat *buffer );
extern void __attribute__((__stdcall__)) glPassThrough( GLfloat token );
extern void __attribute__((__stdcall__)) glSelectBuffer( GLsizei size, GLuint *buffer );
extern void __attribute__((__stdcall__)) glInitNames( void );
extern void __attribute__((__stdcall__)) glLoadName( GLuint name );
extern void __attribute__((__stdcall__)) glPushName( GLuint name );
extern void __attribute__((__stdcall__)) glPopName( void );




extern void __attribute__((__stdcall__)) glGenTextures( GLsizei n, GLuint *textures );
extern void __attribute__((__stdcall__)) glDeleteTextures( GLsizei n, const GLuint *textures);
extern void __attribute__((__stdcall__)) glBindTexture( GLenum target, GLuint texture );
extern void __attribute__((__stdcall__)) glPrioritizeTextures( GLsizei n, const GLuint *textures, const GLclampf *priorities );
extern GLboolean __attribute__((__stdcall__)) glAreTexturesResident( GLsizei n, const GLuint *textures, GLboolean *residences );
extern GLboolean __attribute__((__stdcall__)) glIsTexture( GLuint texture );

extern void __attribute__((__stdcall__)) glTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels );
extern void __attribute__((__stdcall__)) glTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels );
extern void __attribute__((__stdcall__)) glCopyTexImage1D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border );
extern void __attribute__((__stdcall__)) glCopyTexImage2D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border );
extern void __attribute__((__stdcall__)) glCopyTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width );
extern void __attribute__((__stdcall__)) glCopyTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height );

extern void __attribute__((__stdcall__)) glVertexPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glNormalPointer( GLenum type, GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glColorPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glIndexPointer( GLenum type, GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glTexCoordPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glEdgeFlagPointer( GLsizei stride, const GLvoid *ptr );
extern void __attribute__((__stdcall__)) glGetPointerv( GLenum pname, GLvoid **params );
extern void __attribute__((__stdcall__)) glArrayElement( GLint i );
extern void __attribute__((__stdcall__)) glDrawArrays( GLenum mode, GLint first, GLsizei count );
extern void __attribute__((__stdcall__)) glDrawElements( GLenum mode, GLsizei count, GLenum type, const GLvoid *indices );
extern void __attribute__((__stdcall__)) glInterleavedArrays( GLenum format, GLsizei stride, const GLvoid *pointer );

