
typedef struct GLUnurbs GLUnurbs;
typedef struct GLUquadric GLUquadric;
typedef struct GLUtesselator GLUtesselator;


typedef GLUnurbs GLUnurbsObj;
typedef GLUquadric GLUquadricObj;
typedef GLUtesselator GLUtesselatorObj;
typedef GLUtesselator GLUtriangulatorObj;

typedef void (__attribute__((__stdcall__)) *_GLUfuncptr)();

extern void __attribute__((__stdcall__)) gluBeginCurve (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluBeginPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluBeginSurface (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluBeginTrim (GLUnurbs* nurb);
extern GLint __attribute__((__stdcall__)) gluBuild1DMipmaps (GLenum target, GLint internalFormat, GLsizei width, GLenum format, GLenum type, const void *data);
extern GLint __attribute__((__stdcall__)) gluBuild2DMipmaps (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *data);
extern void __attribute__((__stdcall__)) gluCylinder (GLUquadric* quad, GLdouble base, GLdouble top, GLdouble height, GLint slices, GLint stacks);
extern void __attribute__((__stdcall__)) gluDeleteNurbsRenderer (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluDeleteQuadric (GLUquadric* quad);
extern void __attribute__((__stdcall__)) gluDeleteTess (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluDisk (GLUquadric* quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops);
extern void __attribute__((__stdcall__)) gluEndCurve (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluEndPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluEndSurface (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluEndTrim (GLUnurbs* nurb);
extern const GLubyte * __attribute__((__stdcall__)) gluErrorString (GLenum error);
extern const wchar_t * __attribute__((__stdcall__)) gluErrorUnicodeStringEXT (GLenum error);
extern void __attribute__((__stdcall__)) gluGetNurbsProperty (GLUnurbs* nurb, GLenum property, GLfloat* data);
extern const GLubyte * __attribute__((__stdcall__)) gluGetString (GLenum name);
extern void __attribute__((__stdcall__)) gluGetTessProperty (GLUtesselator* tess, GLenum which, GLdouble* data);
extern void __attribute__((__stdcall__)) gluLoadSamplingMatrices (GLUnurbs* nurb, const GLfloat *model, const GLfloat *perspective, const GLint *view);
extern void __attribute__((__stdcall__)) gluLookAt (GLdouble eyeX, GLdouble eyeY, GLdouble eyeZ, GLdouble centerX, GLdouble centerY, GLdouble centerZ, GLdouble upX, GLdouble upY, GLdouble upZ);
extern GLUnurbs* __attribute__((__stdcall__)) gluNewNurbsRenderer (void);
extern GLUquadric* __attribute__((__stdcall__)) gluNewQuadric (void);
extern GLUtesselator* __attribute__((__stdcall__)) gluNewTess (void);
extern void __attribute__((__stdcall__)) gluNextContour (GLUtesselator* tess, GLenum type);
extern void __attribute__((__stdcall__)) gluNurbsCallback (GLUnurbs* nurb, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluNurbsCurve (GLUnurbs* nurb, GLint knotCount, GLfloat *knots, GLint stride, GLfloat *control, GLint order, GLenum type);
extern void __attribute__((__stdcall__)) gluNurbsProperty (GLUnurbs* nurb, GLenum property, GLfloat value);
extern void __attribute__((__stdcall__)) gluNurbsSurface (GLUnurbs* nurb, GLint sKnotCount, GLfloat* sKnots, GLint tKnotCount, GLfloat* tKnots, GLint sStride, GLint tStride, GLfloat* control, GLint sOrder, GLint tOrder, GLenum type);
extern void __attribute__((__stdcall__)) gluOrtho2D (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top);
extern void __attribute__((__stdcall__)) gluPartialDisk (GLUquadric* quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops, GLdouble start, GLdouble sweep);
extern void __attribute__((__stdcall__)) gluPerspective (GLdouble fovy, GLdouble aspect, GLdouble zNear, GLdouble zFar);
extern void __attribute__((__stdcall__)) gluPickMatrix (GLdouble x, GLdouble y, GLdouble delX, GLdouble delY, GLint *viewport);
extern GLint __attribute__((__stdcall__)) gluProject (GLdouble objX, GLdouble objY, GLdouble objZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble* winX, GLdouble* winY, GLdouble* winZ);
extern void __attribute__((__stdcall__)) gluPwlCurve (GLUnurbs* nurb, GLint count, GLfloat* data, GLint stride, GLenum type);
extern void __attribute__((__stdcall__)) gluQuadricCallback (GLUquadric* quad, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluQuadricDrawStyle (GLUquadric* quad, GLenum draw);
extern void __attribute__((__stdcall__)) gluQuadricNormals (GLUquadric* quad, GLenum normal);
extern void __attribute__((__stdcall__)) gluQuadricOrientation (GLUquadric* quad, GLenum orientation);
extern void __attribute__((__stdcall__)) gluQuadricTexture (GLUquadric* quad, GLboolean texture);
extern GLint __attribute__((__stdcall__)) gluScaleImage (GLenum format, GLsizei wIn, GLsizei hIn, GLenum typeIn, const void *dataIn, GLsizei wOut, GLsizei hOut, GLenum typeOut, GLvoid* dataOut);
extern void __attribute__((__stdcall__)) gluSphere (GLUquadric* quad, GLdouble radius, GLint slices, GLint stacks);
extern void __attribute__((__stdcall__)) gluTessBeginContour (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessBeginPolygon (GLUtesselator* tess, GLvoid* data);
extern void __attribute__((__stdcall__)) gluTessCallback (GLUtesselator* tess, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluTessEndContour (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessEndPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessNormal (GLUtesselator* tess, GLdouble valueX, GLdouble valueY, GLdouble valueZ);
extern void __attribute__((__stdcall__)) gluTessProperty (GLUtesselator* tess, GLenum which, GLdouble data);
extern void __attribute__((__stdcall__)) gluTessVertex (GLUtesselator* tess, GLdouble *location, GLvoid* data);
extern GLint __attribute__((__stdcall__)) gluUnProject (GLdouble winX, GLdouble winY, GLdouble winZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble* objX, GLdouble* objY, GLdouble* objZ);
extern GLint __attribute__((__stdcall__)) gluUnProject4 (GLdouble winX, GLdouble winY, GLdouble winZ, GLdouble clipW, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble nearVal, GLdouble farVal, GLdouble* objX, GLdouble* objY, GLdouble* objZ, GLdouble* objW);
