
typedef struct GLUnurbs GLUnurbs;
typedef struct GLUquadric GLUquadric;
typedef struct GLUtesselator GLUtesselator;


typedef GLUnurbs GLUnurbsObj;
typedef GLUquadric GLUquadricObj;
typedef GLUtesselator GLUtesselatorObj;
typedef GLUtesselator GLUtriangulatorObj;

static const int GLU_FALSE = 0;
static const int GLU_TRUE = 1;
static const int GLU_VERSION_1_1 = 1;
static const int GLU_VERSION_1_2 = 1;
static const int GLU_VERSION = 100800;
static const int GLU_EXTENSIONS = 100801;
static const int GLU_INVALID_ENUM = 100900;
static const int GLU_INVALID_VALUE = 100901;
static const int GLU_OUT_OF_MEMORY = 100902;
static const int GLU_INVALID_OPERATION = 100904;
static const int GLU_OUTLINE_POLYGON = 100240;
static const int GLU_OUTLINE_PATCH = 100241;
static const int GLU_NURBS_ERROR1 = 100251;
static const int GLU_NURBS_ERROR2 = 100252;
static const int GLU_NURBS_ERROR3 = 100253;
static const int GLU_NURBS_ERROR4 = 100254;
static const int GLU_NURBS_ERROR5 = 100255;
static const int GLU_NURBS_ERROR6 = 100256;
static const int GLU_NURBS_ERROR7 = 100257;
static const int GLU_NURBS_ERROR8 = 100258;
static const int GLU_NURBS_ERROR9 = 100259;
static const int GLU_NURBS_ERROR10 = 100260;
static const int GLU_NURBS_ERROR11 = 100261;
static const int GLU_NURBS_ERROR12 = 100262;
static const int GLU_NURBS_ERROR13 = 100263;
static const int GLU_NURBS_ERROR14 = 100264;
static const int GLU_NURBS_ERROR15 = 100265;
static const int GLU_NURBS_ERROR16 = 100266;
static const int GLU_NURBS_ERROR17 = 100267;
static const int GLU_NURBS_ERROR18 = 100268;
static const int GLU_NURBS_ERROR19 = 100269;
static const int GLU_NURBS_ERROR20 = 100270;
static const int GLU_NURBS_ERROR21 = 100271;
static const int GLU_NURBS_ERROR22 = 100272;
static const int GLU_NURBS_ERROR23 = 100273;
static const int GLU_NURBS_ERROR24 = 100274;
static const int GLU_NURBS_ERROR25 = 100275;
static const int GLU_NURBS_ERROR26 = 100276;
static const int GLU_NURBS_ERROR27 = 100277;
static const int GLU_NURBS_ERROR28 = 100278;
static const int GLU_NURBS_ERROR29 = 100279;
static const int GLU_NURBS_ERROR30 = 100280;
static const int GLU_NURBS_ERROR31 = 100281;
static const int GLU_NURBS_ERROR32 = 100282;
static const int GLU_NURBS_ERROR33 = 100283;
static const int GLU_NURBS_ERROR34 = 100284;
static const int GLU_NURBS_ERROR35 = 100285;
static const int GLU_NURBS_ERROR36 = 100286;
static const int GLU_NURBS_ERROR37 = 100287;
static const int GLU_AUTO_LOAD_MATRIX = 100200;
static const int GLU_CULLING = 100201;
static const int GLU_SAMPLING_TOLERANCE = 100203;
static const int GLU_DISPLAY_MODE = 100204;
static const int GLU_PARAMETRIC_TOLERANCE = 100202;
static const int GLU_SAMPLING_METHOD = 100205;
static const int GLU_U_STEP = 100206;
static const int GLU_V_STEP = 100207;
static const int GLU_PATH_LENGTH = 100215;
static const int GLU_PARAMETRIC_ERROR = 100216;
static const int GLU_DOMAIN_DISTANCE = 100217;
static const int GLU_MAP1_TRIM_2 = 100210;
static const int GLU_MAP1_TRIM_3 = 100211;
static const int GLU_POINT = 100010;
static const int GLU_LINE = 100011;
static const int GLU_FILL = 100012;
static const int GLU_SILHOUETTE = 100013;
static const int GLU_ERROR = 100103;
static const int GLU_SMOOTH = 100000;
static const int GLU_FLAT = 100001;
static const int GLU_NONE = 100002;
static const int GLU_OUTSIDE = 100020;
static const int GLU_INSIDE = 100021;
static const int GLU_TESS_BEGIN = 100100;
static const int GLU_BEGIN = 100100;
static const int GLU_TESS_VERTEX = 100101;
static const int GLU_VERTEX = 100101;
static const int GLU_TESS_END = 100102;
static const int GLU_END = 100102;
static const int GLU_TESS_ERROR = 100103;
static const int GLU_TESS_EDGE_FLAG = 100104;
static const int GLU_EDGE_FLAG = 100104;
static const int GLU_TESS_COMBINE = 100105;
static const int GLU_TESS_BEGIN_DATA = 100106;
static const int GLU_TESS_VERTEX_DATA = 100107;
static const int GLU_TESS_END_DATA = 100108;
static const int GLU_TESS_ERROR_DATA = 100109;
static const int GLU_TESS_EDGE_FLAG_DATA = 100110;
static const int GLU_TESS_COMBINE_DATA = 100111;
static const int GLU_CW = 100120;
static const int GLU_CCW = 100121;
static const int GLU_INTERIOR = 100122;
static const int GLU_EXTERIOR = 100123;
static const int GLU_UNKNOWN = 100124;
static const int GLU_TESS_WINDING_RULE = 100140;
static const int GLU_TESS_BOUNDARY_ONLY = 100141;
static const int GLU_TESS_TOLERANCE = 100142;
static const int GLU_TESS_ERROR1 = 100151;
static const int GLU_TESS_ERROR2 = 100152;
static const int GLU_TESS_ERROR3 = 100153;
static const int GLU_TESS_ERROR4 = 100154;
static const int GLU_TESS_ERROR5 = 100155;
static const int GLU_TESS_ERROR6 = 100156;
static const int GLU_TESS_ERROR7 = 100157;
static const int GLU_TESS_ERROR8 = 100158;
static const int GLU_TESS_MISSING_BEGIN_POLYGON = 100151;
static const int GLU_TESS_MISSING_BEGIN_CONTOUR = 100152;
static const int GLU_TESS_MISSING_END_POLYGON = 100153;
static const int GLU_TESS_MISSING_END_CONTOUR = 100154;
static const int GLU_TESS_COORD_TOO_LARGE = 100155;
static const int GLU_TESS_NEED_COMBINE_CALLBACK = 100156;
static const int GLU_TESS_WINDING_ODD = 100130;
static const int GLU_TESS_WINDING_NONZERO = 100131;
static const int GLU_TESS_WINDING_POSITIVE = 100132;
static const int GLU_TESS_WINDING_NEGATIVE = 100133;
static const int GLU_TESS_WINDING_ABS_GEQ_TWO = 100134;
static const int GLU_INCOMPATIBLE_GL_VERSION = 100903;

typedef void (__attribute__((__stdcall__)) *_GLUfuncptr)();

extern void __attribute__((__stdcall__)) gluBeginCurve (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluBeginPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluBeginSurface (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluBeginTrim (GLUnurbs* nurb);
extern GLint __attribute__((__stdcall__)) gluBuild1DMipmaps (GLenum target, GLint internalFormat, GLsizei width, GLenum format, GLenum type, const void *data);
extern GLint __attribute__((__stdcall__)) gluBuild2DMipmaps (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *data);
extern void __attribute__((__stdcall__)) gluCylinder (GLUquadric* quad, GLdouble base, GLdouble top, GLdouble height, GLint slices, GLint stacks);
extern void __attribute__((__stdcall__)) gluDeleteNurbsRenderer (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluDeleteQuadric (GLUquadric* quad);
extern void __attribute__((__stdcall__)) gluDeleteTess (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluDisk (GLUquadric* quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops);
extern void __attribute__((__stdcall__)) gluEndCurve (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluEndPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluEndSurface (GLUnurbs* nurb);
extern void __attribute__((__stdcall__)) gluEndTrim (GLUnurbs* nurb);
extern const GLubyte * __attribute__((__stdcall__)) gluErrorString (GLenum error);
extern const wchar_t * __attribute__((__stdcall__)) gluErrorUnicodeStringEXT (GLenum error);
extern void __attribute__((__stdcall__)) gluGetNurbsProperty (GLUnurbs* nurb, GLenum property, GLfloat* data);
extern const GLubyte * __attribute__((__stdcall__)) gluGetString (GLenum name);
extern void __attribute__((__stdcall__)) gluGetTessProperty (GLUtesselator* tess, GLenum which, GLdouble* data);
extern void __attribute__((__stdcall__)) gluLoadSamplingMatrices (GLUnurbs* nurb, const GLfloat *model, const GLfloat *perspective, const GLint *view);
extern void __attribute__((__stdcall__)) gluLookAt (GLdouble eyeX, GLdouble eyeY, GLdouble eyeZ, GLdouble centerX, GLdouble centerY, GLdouble centerZ, GLdouble upX, GLdouble upY, GLdouble upZ);
extern GLUnurbs* __attribute__((__stdcall__)) gluNewNurbsRenderer (void);
extern GLUquadric* __attribute__((__stdcall__)) gluNewQuadric (void);
extern GLUtesselator* __attribute__((__stdcall__)) gluNewTess (void);
extern void __attribute__((__stdcall__)) gluNextContour (GLUtesselator* tess, GLenum type);
extern void __attribute__((__stdcall__)) gluNurbsCallback (GLUnurbs* nurb, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluNurbsCurve (GLUnurbs* nurb, GLint knotCount, GLfloat *knots, GLint stride, GLfloat *control, GLint order, GLenum type);
extern void __attribute__((__stdcall__)) gluNurbsProperty (GLUnurbs* nurb, GLenum property, GLfloat value);
extern void __attribute__((__stdcall__)) gluNurbsSurface (GLUnurbs* nurb, GLint sKnotCount, GLfloat* sKnots, GLint tKnotCount, GLfloat* tKnots, GLint sStride, GLint tStride, GLfloat* control, GLint sOrder, GLint tOrder, GLenum type);
extern void __attribute__((__stdcall__)) gluOrtho2D (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top);
extern void __attribute__((__stdcall__)) gluPartialDisk (GLUquadric* quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops, GLdouble start, GLdouble sweep);
extern void __attribute__((__stdcall__)) gluPerspective (GLdouble fovy, GLdouble aspect, GLdouble zNear, GLdouble zFar);
extern void __attribute__((__stdcall__)) gluPickMatrix (GLdouble x, GLdouble y, GLdouble delX, GLdouble delY, GLint *viewport);
extern GLint __attribute__((__stdcall__)) gluProject (GLdouble objX, GLdouble objY, GLdouble objZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble* winX, GLdouble* winY, GLdouble* winZ);
extern void __attribute__((__stdcall__)) gluPwlCurve (GLUnurbs* nurb, GLint count, GLfloat* data, GLint stride, GLenum type);
extern void __attribute__((__stdcall__)) gluQuadricCallback (GLUquadric* quad, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluQuadricDrawStyle (GLUquadric* quad, GLenum draw);
extern void __attribute__((__stdcall__)) gluQuadricNormals (GLUquadric* quad, GLenum normal);
extern void __attribute__((__stdcall__)) gluQuadricOrientation (GLUquadric* quad, GLenum orientation);
extern void __attribute__((__stdcall__)) gluQuadricTexture (GLUquadric* quad, GLboolean texture);
extern GLint __attribute__((__stdcall__)) gluScaleImage (GLenum format, GLsizei wIn, GLsizei hIn, GLenum typeIn, const void *dataIn, GLsizei wOut, GLsizei hOut, GLenum typeOut, GLvoid* dataOut);
extern void __attribute__((__stdcall__)) gluSphere (GLUquadric* quad, GLdouble radius, GLint slices, GLint stacks);
extern void __attribute__((__stdcall__)) gluTessBeginContour (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessBeginPolygon (GLUtesselator* tess, GLvoid* data);
extern void __attribute__((__stdcall__)) gluTessCallback (GLUtesselator* tess, GLenum which, _GLUfuncptr CallBackFunc);
extern void __attribute__((__stdcall__)) gluTessEndContour (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessEndPolygon (GLUtesselator* tess);
extern void __attribute__((__stdcall__)) gluTessNormal (GLUtesselator* tess, GLdouble valueX, GLdouble valueY, GLdouble valueZ);
extern void __attribute__((__stdcall__)) gluTessProperty (GLUtesselator* tess, GLenum which, GLdouble data);
extern void __attribute__((__stdcall__)) gluTessVertex (GLUtesselator* tess, GLdouble *location, GLvoid* data);
extern GLint __attribute__((__stdcall__)) gluUnProject (GLdouble winX, GLdouble winY, GLdouble winZ, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble* objX, GLdouble* objY, GLdouble* objZ);
extern GLint __attribute__((__stdcall__)) gluUnProject4 (GLdouble winX, GLdouble winY, GLdouble winZ, GLdouble clipW, const GLdouble *model, const GLdouble *proj, const GLint *view, GLdouble nearVal, GLdouble farVal, GLdouble* objX, GLdouble* objY, GLdouble* objZ, GLdouble* objW);
